### ISSUE TITLE
Error message: Cannot read properties of undefined (reading ‘attributes’)

### ISSUE THREAD

**Issue by Silverridge** [nidayand/lovelace-pollen-card#2]
The card isn't showing any information, just the error message: `Cannot read properties of undefined (reading ‘attributes’)`.

![pollen](https://user-images.githubusercontent.com/52776523/188115542-0155d864-bf42-410d-9211-674f970da9b6.png)

**Comment by nidayand** [comment]
I've tested with Pollenprognos integration for Borlänge and it works fine.  Please verify your integration component

![image](https://user-images.githubusercontent.com/2181965/221966433-083a22f1-52a6-4179-a2ca-9b3800d0801e.png)
