### ISSUE TITLE
Integration cannot be installed through HACS

### ISSUE THREAD

**Issue by Silverridge** [nidayand/lovelace-pollen-card#3]
The integration renders an error message when trying to install it through HACS
![integration](https://user-images.githubusercontent.com/52776523/188116492-c89ce787-5892-4ac7-9b8a-e0a7d6a650fa.png)

**Comment by nidayand** [comment]
Please describe your config and actions. I've tested on a clean install of HACS and it works fine to add and install the plugin

![image](https://user-images.githubusercontent.com/2181965/221967234-dd7d3722-cbdc-449a-9d92-89d72edbc7f3.png)
